i = input('Digite algo: ')
print('O tipo primitivo desse valor: ',type(i))
print('Só tem espaço?: ', i.isspace())
print('É um numero? ',i.isnumeric())
print('É alfabético? ', i.isalpha())
print('É alfanumerico? ', i.isalnum())
print('Esta em maiúsculo? ', i.isupper())
print('Esta em minúsculo? ', i.islower())
print('Esta capitaliza? ', i.istitle())